Django Projeto/Site/Site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings;
from django.conf.urls.static import static

# //junção de todas as urls do sistema
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),
    path('', include('usuarios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django Projeto/Site/cadastros/urls.py
from django.urls import path
from .views import FuncionarioCreate, PessoaCreate, FuncionarioUpdate, PessoaUpdate, FichaCreate, FichaUpdate
from .views import PessoaDelete, FuncionarioDelete, FichaDelete
from .views import PessoaList, FuncionarioList, FichaList
from django.contrib.auth.mixins import LoginRequiredMixin

urlpatterns = [
    path('cadastrar/funcionario/', FuncionarioCreate.as_view(), name="cadastrar-funcionario"),
    path('cadastrar/pessoa/', PessoaCreate.as_view(), name="cadastrar-pessoa"),
    path('cadastrar/ficha/', FichaCreate.as_view(), name="cadastrar-ficha"),

    path('editar/funcionario/<int:pk>/', FuncionarioUpdate.as_view(), name="editar-funcionario"),
    path('editar/pessoa/<int:pk>/', PessoaUpdate.as_view(), name="editar-pessoa"),
    path('editar/ficha/<int:pk>/', FichaUpdate.as_view(), name="editar-ficha"),

    path('excluir/funcionario/<int:pk>/', FuncionarioDelete.as_view(), name="excluir-funcionario"),
    path('excluir/pessoa/<int:pk>/', PessoaDelete.as_view(), name="excluir-pessoa"),
    path('excluir/ficha/<int:pk>/', FichaDelete.as_view(), name="excluir-ficha"),

    path('listar/pessoa/', PessoaList.as_view(), name="listar-pessoa"),
    path('listar/funcionario/', FuncionarioList.as_view(), name="listar-funcionario"),
    path('listar/ficha/', FichaList.as_view(), name="listar-ficha"),

    
    
]

Django Projeto/Site/cadastros/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Pessoa(models.Model):
    nome = models.CharField(max_length=50)
    endereco = models.CharField(max_length=50, verbose_name="Endereço", unique=True)
    telefone = models.CharField(max_length=50)
    email = models.CharField(max_length=50, unique=True)
    cpf = models.CharField(max_length=50)
    arquivo = models.FileField(upload_to='pdf/')

    def __str__(self):
        return "{} ({})".format(self.nome, self.endereco)

class Funcionario(models.Model):
    nome = models.CharField(max_length=50)
    endereco = models.CharField(max_length=50, verbose_name="Endereço", unique=True)
    telefone = models.CharField(max_length=50)
    email = models.CharField(max_length=50, unique=True)
    cpf = models.CharField(max_length=50)

    def __str__(self):
        return "{} ({})".format(self.nome, self.endereco)

class Ficha(models.Model):
    
    data = models.CharField(max_length=50)
    qtd = models .IntegerField()
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)

    funcionario = models.ForeignKey(Funcionario, on_delete = models.PROTECT)
    pessoa = models.ForeignKey(Pessoa, on_delete = models.PROTECT)
    
    def __str__(self):
        return "{} ({})".format(self.data, self.qtd)

Django Projeto/Site/cadastros/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from .models import Funcionario, Pessoa, Ficha
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import GroupRequiredMixin
from django.shortcuts import get_object_or_404

# Create your views here.
class FuncionarioCreate(GroupRequiredMixin, LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    group_required = u"Administrador"
    model = Funcionario
    fields = ['nome','endereco','telefone', 'email', 'cpf']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('index')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = " Cadastro de Funcionário"
        return context


class PessoaCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = Pessoa
    fields = ['nome','endereco','telefone', 'email', 'cpf', 'arquivo']
    template_name = 'cadastros/form-upload.html'
    success_url = reverse_lazy('index')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = " Cadastro de Pessoa"
        return context

class FichaCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = Ficha
    fields = ['data','qtd','funcionario', 'pessoa']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('index')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = " Cadastro de Ficha"
        return context


    def form_valid(self, form):
        #objeto não criado
        form.instance.usuario = self.request.user
        url= super().form_valid(form)
        #objeto criado
        #self.object.pessoa = "teste: "+ self.object.pessoa
        #self.object.save()  
        return url

####UPDATE#########################################################################
class PessoaUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    model = Pessoa
    fields = ['nome','endereco','telefone', 'email', 'cpf', 'arquivo']
    template_name = 'cadastros/form-upload.html'
    success_url = reverse_lazy('listar-pessoa')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = " Edição de Pessoa"
        return context


class FuncionarioUpdate(GroupRequiredMixin, LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    group_required = u"Administrador"
    model = Funcionario
    fields = ['nome','endereco','telefone', 'email', 'cpf']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-funcinario')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = " Cadastro de Funcionário"
        return context


class FichaUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    model = Ficha
    fields = ['data','qtd','funcionario', 'pessoa']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-ficha')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['titulo'] = " Cadastro de Ficha"
        return context


    # #aula 22-----------o usuario tal só ve os cadastros dele----------------------------------------
    def get_object(self, queryset=None):
        # get_object_or_404(Classe, atr="isso", atr2=val2 )
        #self.object = Ficha.objects.get(pk=self.kwargs['pk'], usuario=self.request.user)
        self.object = get_object_or_404(Ficha, pk=self.kwargs['pk'], usuario=self.request.user)
        return self.object

    ### DELETE ###################################################################
class PessoaDelete(LoginRequiredMixin, DeleteView):
        login_url = reverse_lazy('login')
        model = Pessoa
        template_name = 'cadastros/form-excluir.html'
        success_url = reverse_lazy('listar-pessoa')

class FuncionarioDelete(GroupRequiredMixin, LoginRequiredMixin, DeleteView):
        login_url = reverse_lazy('login')
        group_required = u"Administrador"
        model = Funcionario
        template_name = 'cadastros/form-excluir.html'
        success_url = reverse_lazy('listar-funcinario')

class FichaDelete(LoginRequiredMixin, DeleteView):
        login_url = reverse_lazy('login')
        model = Ficha
        template_name = 'cadastros/form-excluir.html'
        success_url = reverse_lazy('listar-ficha')
        #aula22
        def get_object(self, queryset=None):
        # get_object_or_404(Classe, atr="isso", atr2=val2 )
        #self.object = Ficha.objects.get(pk=self.kwargs['pk'], usuario=self.request.user)
            self.object = get_object_or_404(Ficha, pk=self.kwargs['pk'], usuario=self.request.user)
            return self.object


        ### LISTAR ###################################################################

class PessoaList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Pessoa
    template_name = 'cadastros/listas/pessoa.html'

class FuncionarioList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Funcionario
    template_name = 'cadastros/listas/funcionario.html'

class FichaList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Ficha
    template_name = 'cadastros/listas/ficha.html'
    #ta funcionando, só desabilitei pq não tem necessidade
    #aula 21-------------------o usuario tal só ve os cadastros dele-------------------------------
    # def get_queryset(self):
    # #     ##padrao self.object_list = ficha.objects.all()
    # #     #registros por usuario
    #     self.object_list = Ficha.objects.filter(usuario=self.request.user)
    #     return self.object_list

Django Projeto/Site/cadastros/templates/cadastros/form-excluir.html
<!-- Para carregar o modelo -->
{% extends 'paginas/modelo.html' %}
<!-- Para carregar a imagem -->
{% load static %}
{% load crispy_forms_tags %}

<!-- colocar apenas o que vai substuir do modelo de base -->
{% block titulo %}
<title>Excluir Registros</title>
{% endblock %}
<!-- para excluir um desses modulos -->
{% block destaque %}
    <!-- só não colocar nada dentro -->
{% endblock %}
<!-- para substituir o conteudo -->
{% block conteudo %}
    <h3>Excluir registros </h3>
    <p>confirme para excluir definitivamente</p>

    <form action="" method="POST">

        <p>
            Deseja excluir o registro: <b>{{ object }}</b>?
        </p>

        {% csrf_token %} 
        {{ form|crispy }}

        <button type="submit" class="btn btn-danger">Exluir</button>
      </form>
     
{% endblock %}

Django Projeto/Site/cadastros/templates/cadastros/form-upload.html
<!-- Para carregar o modelo -->
{% extends 'paginas/modelo.html' %}
<!-- Para carregar a imagem -->
{% load static %}
{% load crispy_forms_tags %}

<!-- colocar apenas o que vai substuir do modelo de base -->
{% block titulo %}
<title>Cadastro</title>
{% endblock %}
<!-- para excluir um desses modulos -->
{% block destaque %}
    <!-- só não colocar nada dentro -->
{% endblock %}
<!-- para substituir o conteudo -->
{% block conteudo %}
    <h3>{{titulo}} </h3>
    <p>insira os dados</p>

    <form action="" method="POST" enctype="multipart/form-data">
        
        {% csrf_token %} 
        {{ form|crispy }}

        <button type="submit" class="btn btn-primary">Cadastrar</button>
      </form>
     
{% endblock %}
{% block scripts %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script> 
   $(document).ready(function(){
    alert("importação Jquerry Ok");
    $("#id_cpf").mask("000.000.000-00");
    // $("#id_telefone").mask("(00) 00000-0000");
    var SPMaskBehavior = function (val) {
        return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
    },
    spOptions = {
    onKeyPress: function(val, e, field, options) {
        field.mask(SPMaskBehavior.apply({}, arguments), options);
        }
    };

    $('#id_telefone').mask(SPMaskBehavior, spOptions);
    
   
   });
</script>
{% endblock %}

Django Projeto/Site/cadastros/templates/cadastros/form.html
<!-- Para carregar o modelo -->
{% extends 'paginas/modelo.html' %}
<!-- Para carregar a imagem -->
{% load static %}
{% load crispy_forms_tags %}

<!-- colocar apenas o que vai substuir do modelo de base -->
{% block titulo %}
<title>Cadastro</title>
{% endblock %}
<!-- para excluir um desses modulos -->
{% block destaque %}
    <!-- só não colocar nada dentro -->
{% endblock %}
<!-- para substituir o conteudo -->
{% block conteudo %}
    <h3>{{titulo}} </h3>
    <p>insira os dados</p>

    <form action="" method="POST">
        
        {% csrf_token %} 
        {{ form|crispy }}

        <button type="submit" class="btn btn-primary">Cadastrar</button>
      </form>
     
{% endblock %}
{% block scripts %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script> 
   $(document).ready(function(){
    alert("importação Jquerry Ok");
    $("#id_cpf").mask("000.000.000-00");
    // $("#id_telefone").mask("(00) 00000-0000");
    var SPMaskBehavior = function (val) {
        return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
    },
    spOptions = {
    onKeyPress: function(val, e, field, options) {
        field.mask(SPMaskBehavior.apply({}, arguments), options);
        }
    };

    $('#id_telefone').mask(SPMaskBehavior, spOptions);
    
   
   });
</script>
{% endblock %}